[3dtanks]
tags="game,public-domain"
title="3D Tanks"
disc="3D_Tanks.zip"
author="Stuart Cupit and Simon Cruise"
year=1989

[bloxed]
tags="game,public-domain"
disc="Bloxed.zip"
title="Bloxed"
description="Fun Tetris clone"
year=1995
author="Steven Singer"

[2067bc]
title="2067BC Demo"
year=1992
tags="game,ex-commercial"
publisher="Oregan"
description="Prehistoric themed sideways scroller"
disc="2067BC.zip"

## PD Games
#3D_Tanks.zip 3D Tanks
#Bloxed.zip Bloxed
#
## Ex-Commercial Games
#2067BC.zip 2067 BC
#Aliped.zip Aliped
#BBvsDP.zip Bobby Blockhead vs. The Dark Planet
#bhis.zip Bug Hunder in Space
#bug1.zip Bug Hunter and Moon Dask
#Chaos.zip Spheres of Chaos
#Cycloids.zip Cyclois
#Elite.zip Elite
#Hamsters.zip Hamsters
#
## Game Demos
#GameDemos02.zip Flashback
#GameDemos03.zip DinoSaw
#GameDemos04.zip Hex / Magnetoids
#GameDemos05.zip Repton 4 / James Pond II: Robocod
#GameDemos06.zip Golf / Quark
#GameDemos07.zip Prime Solver
#GameDemos08.zip Heimdall / Magic Pockets / Populous
#GameDemos11.zip Sensible Soccer / TechnoDream
#GameDemos12.zip Starfighter 3000
#GameDemos13.zip Cataclysm / James Pond
#GameDemos14.zip Arcturus
#GameDemos15.zip Alone in the Dark
#Lander.zip Lander
#GameDemos16.zip Lemmings / Oh No! More Lemmings
#GameDemos17.zip Fervour
#GameDemos18.zip S.W.I.V / Scorpius
#GameDemos19.zip Bambuzle
#GameDemos20.zip Crystal Maze
#GameDemos22.zip Diggers
#GameDemos24.zip Chocks Away
#Hamsters.zip
#Lander.zip
#MrDoo.zip
#Nebulus.zip
#PDGames04.zip
#PDGames05.zip Rockfall
#PDGames06.zip
#SWIV.zip